config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create ]
  end

  resources :doses, only: [:destroy]
  resources :ingredients, only: [:new, :create, :show]

  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  has_attachment :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :description, presence: true, allow_blank: false

  validates_uniqueness_of :cocktail, :scope => :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :restrict_with_exception
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail.id)
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail_id = dose.cocktail_id
    dose.delete
    redirect_to cocktail_path(cocktail_id)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save ? (redirect_to ingredient_path(@ingredient)) : (render :new)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container padded bg-grey-light">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center">Better cocktails on earth</h1>
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="col-xs-12 col-md-4">
            <%= content_tag :div, class: 'card', style: "background-image: url(#{cl_image_path cocktail.photo.path})" do %>
              <div class="card-title">
                <%= cocktail.name %>
              </div>
              <%= link_to '', cocktail_path(cocktail), class: 'card-link' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h2>New cocktail</h2>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.error_notification %>

        <%= f.input :name %>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
    <h1><%= @cocktail.name %></h1>
    <% if @cocktail.photo? %>
      <%= cl_image_tag @cocktail.photo.path, width: 700, height: 400, crop: :fill %>
    <% end %>
    <ul class="list-unstyled">
      <% @doses.each do |dose| %>
        <li>
          <%= dose.description %>
           of
          <%= dose.ingredient.name %>
          <%= link_to dose_path(dose), method: :delete do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= link_to 'BACK', cocktails_path, class: "btn btn-primary" %>
    <%#= link_to 'Add a dose', new_cocktail_dose_path(@cocktail) %>

    <%= button_tag 'Add a dose', class: "btn btn-primary",
      data: { toggle: 'modal', target: "#newDose" } %>
    <!-- Modal -->
    <div class="modal fade" id="newDose" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New dose for '<%= @cocktail.name %>'</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for [@cocktail, @dose] do |f| %>
              <%= f.error_notification %>

              <%= f.input :description %>
              <%= f.association :ingredient, prompt: "Choose an ingredient"%>

              <%= f.button :submit %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h2>New dose for cocktail: <%= @cocktail.name %></h2>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.error_notification %>

        <%= f.input :description %>
        <%= f.association :ingredient, prompt: "Choose an ingredient"%>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>
$

app/views/ingredients/new.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h2>New ingredient</h2>
      <%= simple_form_for(@ingredient) do |f| %>
        <%= f.error_notification %>

        <%= f.input :name %>

        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @ingredient.name %></h1>
      <ul class="list-unstyled">
        <% @ingredient.cocktails.each do |cocktail| %>
          <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
        <% end %>
      </ul>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cocktail-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to new_ingredient_path do %>
      <li class="fa fa-barcode" style="font-size: 40px;"></li>
    <% end %>
    <%= link_to t(".top_call_to_action", default: "New cocktail"), new_cocktail_path,
      class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</div>